bootstrap/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// login
Route::get('/','LoginController@index')->name('/');
Route::post('login.credentials','LoginController@credentials')->name('login.credentials');
// solicitud
Route::resource('solicitud', 'SolicitudController');
Route::post('/agendarCita','SolicitudController@agendarCita')->name('solicitud.agendarCita');
// preCandidatos
Route::get('/preCandidatos/create/{id}', 'PreCandidatoController@create')->name('preCandidatos.create');
Route::post('/preCandidatos/store', 'PreCandidatoController@store')->name('preCandidatos.store');
Route::get('/preCandidatos', 'PreCandidatoController@index')->name('preCandidatos.index');
Route::get('/preCandidatos/edit/{id}', 'PreCandidatoController@edit')->name('preCandidatos.edit');
Route::post('/preCandidatos/update', 'PreCandidatoController@update')->name('preCandidatos.update');
Route::post('/preCandidatos/delete', 'PreCandidatoController@destroy')->name('preCandidatos.destroy');
Route::get('/preCandidatos/show/{id}', 'PreCandidatoController@show')->name('preCandidatos.show');
Route::post('/preCandidatos/foto', 'PreCandidatoController@foto')->name('preCandidatos.foto');
// candidato
Route::get('/candidato', 'CandidatoController@index')->name('candidato.index');
Route::post('/candidato/store', 'CandidatoController@store')->name('candidato.store');
Route::get('/candidato/show/{id}', 'CandidatoController@show')->name('candidato.show');	
Route::post('/candidato/update', 'CandidatoController@update')->name('candidato.update');
// seguimiento
Route::post('/seguimiento/store', 'SeguimientoController@store')->name('seguimiento.store');
Route::post('/seguimiento/update', 'SeguimientoController@update')->name('seguimiento.update');
Route::get('/seguimiento', 'SeguimientoController@index')->name('seguimiento.index');
Route::get('/seguimiento/show/{id}', 'SeguimientoController@show')->name('seguimiento.show');
// empleado
Route::get('/empleado', 'EmpleadoController@index')->name('empleado.index');
Route::get('/empleado/create/{id}', 'EmpleadoController@create')->name('empleado.create');
Route::get('/empleado/edit/{id}', 'EmpleadoController@edit')->name('empleado.edit');
Route::post('/empleado/store', 'EmpleadoController@store')->name('empleado.store');
Route::post('/empleado/update', 'EmpleadoController@update')->name('empleado.update');
Route::get('/empleado/show/{id}', 'EmpleadoController@show')->name('empleado.show');
// catalogos index
Route::get('/catalogos/area', 'CatalogosController@areaIndex')->name('catalogos.area.index');
Route::get('/catalogos/bolsa', 'CatalogosController@bolsaIndex')->name('catalogos.bolsa.index');
Route::get('/catalogos/competencias', 'CatalogosController@competenciaIndex')->name('catalogos.competencias.index');
Route::get('/catalogos/empresa', 'CatalogosController@empresaIndex')->name('catalogos.empresa.index');
Route::get('/catalogos/escolaridad', 'CatalogosController@escolaridadIndex')->name('catalogos.escolaridad.index');
Route::get('/catalogos/etdoCivil', 'CatalogosController@estadoCivilIndex')->name('catalogos.etdoCivil.index');
Route::get('/catalogos/etdoEscolar', 'CatalogosController@etdoEscolaridadIndex')->name('catalogos.etdoEscolar.index');
Route::get('/catalogos/etdoMotivo', 'CatalogosController@etdoMotivoIndex')->name('catalogos.etdoMotivo.index');
Route::get('/catalogos/puesto', 'CatalogosController@puestoIndex')->name('catalogos.puesto.index');
Route::get('/catalogos/tipoPuesto', 'CatalogosController@tipoPuestoIndex')->name('catalogos.tipoPuesto.index');
// catalogos delete
Route::get('/catalogos/destroy', 'CatalogosController@destroy')->name('catalogos.destroy');
// catalogos save
Route::post('/catalogos/saveArea', 'CatalogosController@saveArea')->name('catalogos.saveArea');
Route::post('/catalogos/saveBolsa', 'CatalogosController@saveBolsa')->name('catalogos.saveBolsa');
Route::post('/catalogos/saveCompetencia', 'CatalogosController@saveCompetencia')->name('catalogos.saveCompetencia');
Route::post('/catalogos/saveEmpresa', 'CatalogosController@saveEmpresa')->name('catalogos.saveEmpresa');
Route::post('/catalogos/saveEscolaridad', 'CatalogosController@saveEscolaridad')->name('catalogos.saveEscolaridad');
Route::post('/catalogos/saveEtdoCivil', 'CatalogosController@saveEtdoCivil')->name('catalogos.saveEtdoCivil');
Route::post('/catalogos/saveEtdoEscolar', 'CatalogosController@saveEtdoEscolar')->name('catalogos.saveEtdoEscolar');
Route::post('/catalogos/saveEtdoMotivo', 'CatalogosController@saveEtdoMotivo')->name('catalogos.saveEtdoMotivo');
Route::post('/catalogos/savePuesto', 'CatalogosController@savePuesto')->name('catalogos.savePuesto');
Route::post('/catalogos/saveTipoPuesto', 'CatalogosController@saveTipoPuesto')->name('catalogos.saveTipoPuesto');

Route::get('/prueba','TableController@index')->name('prueba');
Route::get('/prueba/data','TableController@getdata')->name('prueba.getdata');

bootstrap/resources/views/seguimiento/create.blade.php
<div class="modal fade" id="crearSeguimientoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
 aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Crear Seguimiento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form  action="seguimiento/store" method="POST">
          @csrf
          <input type="hidden" class="form-control" name="id" id="id"><br>
          <div class="md-form">
              <input type="text" id="calificacion_rollplay" class="form-control" name="calificacion_rollplay">
              <label for="calificacion_rollplay">Calificacion Rollplay</label>
          </div>
          <div class="md-form">
              <textarea type="text" id="comentarios" class="md-textarea form-control" rows="3" name="comentarios"></textarea>
              <label for="comentarios">Comentarios</label>
          </div>
          <button type="submit" class="btn btn-success" id="guardar">Crear Seguimiento</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        
      </div>
    </div>
  </div>
</div>

bootstrap/resources/views/seguimiento/index.blade.php
@extends('layouts.appLayout')
@section('content')
		<div class="container">
      <ol class="breadcrumb">
    <li class="breadcrumb-item active">Seguimiento</li>
</ol>
		<table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Nombre
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Telefono
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Correo
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Calificacion Rollplay
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Comentarios
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Candidato
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Accion
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>

    </tr>
  </thead>
  <tbody>
  	@foreach($seguimientos as $seguimiento)
    @if($seguimiento->id_estado_motivo == 1 || $seguimiento->id_estado_motivo == 2 || $seguimiento->id_estado_motivo == 100)
    <tr>
      <td>{{$seguimiento->nombre." ".$seguimiento->apellido_paterno." ".$seguimiento->apellido_materno}}</td>
      <td>{{$seguimiento->telefono_movil}}</td>
      <td>{{$seguimiento->email}}</td>
      <td>{{$seguimiento->calificacion_rollplay}}</td>
      <td>{{$seguimiento->comentarios}}</td>
      <td>
        @if($seguimiento->id_estado == 1)
        <a href="{{route('empleado.show',$seguimiento->id)}}" class="btn unique-color white-text btn-sm">Ver empleado</a>
        @else
        <a class="btn unique-color white-text btn-sm" href="{{route('empleado.create',$seguimiento->id)}}">Crear empleado</a>
        @endif
      </td>
      <td>
      <button class= "btn warning-color-dark btn-sm" data-id='{{ $seguimiento->id }}' 
          data-toggle="modal" data-target="#updateSeguimientoModal" data-calificacion = '{{$seguimiento->calificacion_rollplay}}'
          data-comentarios = '{{$seguimiento->comentarios}}'>Modificar</button>
      <button class="btn danger-color-dark btn-sm"  data-toggle="modal" data-target="#deleteModal" 
      data-id='{{ $seguimiento->id }}'>Eliminar</button>
    </td>
    </tr>
    @endif
    @endforeach
  </tbody>
</table>
{{$seguimientos->links()}}
	</div>

  <div class="modal fade" id="updateSeguimientoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
 aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Actualizar Seguimiento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form  action="{{route('seguimiento.update')}}" method="POST">
          @csrf
          <input type="hidden" class="form-control" name="id" id="id"><br>
          <div class="md-form">
              <input type="text" id="calificacion" class="form-control" name="calificacion">
          </div>
          <div class="md-form">
              <textarea type="text" id="comentarios" class="md-textarea form-control" rows="3" name="comentarios"></textarea>
          </div>
          <button type="submit" class="btn btn-success" id="guardar">Actualizar Seguimiento</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

@endsection
@section('scripts')
    <script type="text/javascript">
      $('#updateSeguimientoModal').on('show.bs.modal',function (event) {
         var button = $(event.relatedTarget)
         var id = button.data('id')
         var calificacion = button.data('calificacion')
         var comentarios =button.data('comentarios')
         var modal = $(this)

         modal.find('.modal-body #id').val(id);
         modal.find('.modal-body #calificacion').val(calificacion);
         modal.find('.modal-body #comentarios').val(comentarios);
      })
    </script>
  @endsection
  

bootstrap/resources/views/seguimiento/show.blade.php
@extends('layouts.appLayout')
@section('content')
  <div class="container" style="width: 1000px;">
    <div class="row">
      <div class="col-md-6">
        <label for="nombre">Nombre:</label>
        <label for="">{{$seguimiento->nombre}}</label> <br>
        <label for="nombre">Apellido Paterno:</label>
        <label for="">{{$seguimiento->apellido_paterno}}</label> <br>
        <label for="nombre">Apellido Materno:</label>
        <label for="">{{$seguimiento->apellido_materno}}</label> <br>
        <label for="nombre">Email:</label>
        <label for="">{{$seguimiento->email}}</label> <br>
        <label for="nombre">Telefono Movil:</label>
        <label for="">{{$seguimiento->telefono_movil}}</label> <br>
        <label for="nombre">Calificacion de Rollplay:</label>
        <label for="">{{$seguimiento->calificacion_rollplay}}</label> <br>
        <label for="nombre">Comentarios:</label>
        <label for="">{{$seguimiento->comentarios}}</label> <br>
        <label for="nombre">Estado:</label>
        <label for="">{{$seguimiento->estado}}</label> <br>
      </div>
    </div>
  </div>
@endsection

bootstrap/resources/views/seguimiento/update.blade.php
<div class="modal fade" id="updateSeguimientoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
 aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Actualizar Seguimiento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form  action="seguimiento/update" method="POST">
          @csrf
          <input type="hidden" class="form-control" name="id" id="id"><br>
          <div class="md-form">
              <input type="text" id="calificacion" class="form-control" name="calificacion">
          </div>
          <div class="md-form">
              <textarea type="text" id="comentarios" class="md-textarea form-control" rows="3" name="comentarios"></textarea>
          </div>
          <button type="submit" class="btn btn-success" id="guardar">Actualizar Seguimiento</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        
      </div>
    </div>
  </div>
</div>

bootstrap/resources/views/solicitudes/create.blade.php
@extends('layouts.appLayout')
@section('content')
<div class="container">
	<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('solicitud.index')}}">Solicitudes</a></li>
    <li class="breadcrumb-item active">Crear Solicitud</li>
</ol>
	<div class="row pt-5 mx-auto">
		<h1 class="text-center">Llena la Siguiente Solicitud</h1>
	</div>
	<div class="row">
		<div class="col-md-8 mx-auto">
			@if (count($errors) > 0)
    <div class="alert alert-danger">
    	<p>Corrige los siguientes errores:</p>
        <ul>
            @foreach ($errors->all() as $message)
                <li>{{ $message }}</li>
            @endforeach
        </ul>
    </div>
@endif

			<form action="{{route('solicitud.store')}}" method="post">
				@csrf
				<div class="md-form">
					<input type="text"  class="form-control" name="nombre" value="{{ old('nombre') }}">
					<label for="nombre" >Nombre</label>
				</div>
				<div class="md-form">
					<input type="text"  class="form-control" name="apellido_paterno" value="{{ old('apellido_paterno') }}">
					<label for="apellido_paterno" >Apellido Paterno</label>
				</div>
				<div class="md-form">
					<input type="text"  class="form-control" name="apellido_materno" value="{{ old('apellido_materno') }}">
					<label for="apellido_materno" >Apellido Materno</label>
				</div>
				<div class="md-form">
					<input type="email"  class="form-control" name="email" value="{{ old('email') }}">
					<label for="email" >Email</label>
				</div>
				<div class="md-form">
					<input type="text"  class="form-control" name="telefono" value="{{ old('telefono') }}">
					<label for="telefono" >Telefono</label>
				</div>
				<div class="md-form">

					<select name="bolsaTrabajo" id="" class="form-control">
						<option value="" selected>Bolsa de Trabajo</option>
						@foreach($bolsaTrabajo as $bolsa)
							<option value="{{$bolsa->id}}">{{$bolsa->nombre}}</option>
						@endforeach
					</select>
				</div>
				<button type="submit" class="btn success-color-dark">Registrar</button>
			</form>
		</div>
	</div>
</div>
@endsection

bootstrap/resources/views/solicitudes/index.blade.php
@extends('layouts.appLayout')
@section('content')
	<div class="container">
    <ol class="breadcrumb">
    <li class="breadcrumb-item active">Solicitudes</li>
</ol>
    <a href="{{route('solicitud.create')}}" class="btn success-color-dark">Crear Solicitud</a>
		<table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Nombre
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Telefono
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Correo
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Fecha de Cita
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Cita
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Candidato
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Accion
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
    </tr>
  </thead>
  <tbody>
  	@foreach($solicitudes as $solicitud)
    <tr>
      <td>{{$solicitud->nombre." ".$solicitud->apellido_paterno." ".$solicitud->apellido_materno}}</td>
      <td>{{$solicitud->telefono}}</td>
      <td>{{$solicitud->correo}}</td>
      <td>
      	@if($solicitud->fecha_cita != '')
      		{{$solicitud->fecha_cita}}
		@else
			No hay cita agendada
		@endif
      </td>
      <td>
      	@if($solicitud->fecha_cita != '')
      		<button class="btn unique-color white-text btn-sm" data-id='{{$solicitud->id}}' data-toggle="modal" 
            data-target="#agendarCitaModal">Cambiar Cita</button>
  		@else
  			<button class="btn unique-color white-text btn-sm" data-id='{{ $solicitud->id }}' 
          data-toggle="modal" data-target="#agendarCitaModal">Agendar Cita</button>
		@endif
      </td>
      <td>
      	@if($solicitud->estado == 0 && $solicitud->fecha_cita !=0)
      		<a href="{{route('preCandidatos.create',$solicitud->id)}}" class="btn primary-color-dark text-white btn-sm">Crear Precandidato</a>
  		@elseif($solicitud->estado == 1 && $solicitud->fecha_cita !=0)
  			<a href="{{route('preCandidatos.show',$solicitud->id)}}" class="btn primary-color-dark text-white btn-sm">Ver Precandidato</a>
		@endif
      </td>
      <td>
        <button class="btn warning-color-dark btn-sm" data-id='{{ $solicitud->id }}' data-nombre='{{ $solicitud->nombre }}' 
          data-apellido_paterno='{{ $solicitud->apellido_paterno }}' data-apellido_materno='{{ $solicitud->apellido_materno }}' 
          data-email='{{ $solicitud->correo }}'
          data-telefono='{{ $solicitud->telefono }}'
          data-toggle="modal" data-target="#modificarSolicitudModal">
          Modificar
        </button> 
      </td>
    </tr>
    @endforeach
  </tbody>      
</table>
{{$solicitudes->links()}}
	</div>

  <div class="modal fade" id="agendarCitaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agendar Cita</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form  id="agendarCitaForm" method="POST" action="{{route('solicitud.agendarCita')}}">
          @csrf
          <input type="hidden" class="form-control" name="id" id="id"><br>
          <input type="date" class="form-control" name="fecha" id="fecha"><br>
        <input type="time" class="form-control" name="hora" id="hora"><br>
        <button type="submit" class="btn btn-success" id="agendar">Agendar Cita</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modificarSolicitudModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" 
aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Actualizar Datos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <form action="{{route('solicitud.update','test')}}" method="POST">
        @csrf
        {{method_field('patch')}}
        <input type="hidden" name="id" id="id">
        <div class="md-form">
          <input type="text"  class="form-control" name="nombre" id="nombre">
          
        </div>
        <div class="md-form">
          <input type="text"  class="form-control" name="apellido_paterno"  
          id="apellido_paterno">
    
        </div>
        <div class="md-form">
          <input type="text"  class="form-control" name="apellido_materno" 
          id="apellido_materno">
          
        </div>
        <div class="md-form">
          <input type="email"  class="form-control" name="email"  id="email">
          
        </div>
        <div class="md-form">
          <input type="text"  class="form-control" name="telefono" id="telefono">
          
        </div>
        <div class="md-form">
        </div>
        <input type="submit" class="btn btn-success" value="Registrar">
      </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


@endsection
@section('scripts')
     <script type="text/javascript">
      $('#agendarCitaModal').on('show.bs.modal',function (event) {
         var button = $(event.relatedTarget)
         var id = button.data('id')
         var modal = $(this)

         modal.find('.modal-body #id').val(id);
      })
    </script>
    <script type="text/javascript">
      $('#modificarSolicitudModal').on('show.bs.modal',function (event) {
         var button = $(event.relatedTarget)
         var id = button.data('id')
         var nombre = button.data('nombre')
         var apellido_paterno = button.data('apellido_paterno')
         var apellido_materno = button.data('apellido_materno')
         var email = button.data('email')
         var telefono = button.data('telefono')
         var modal = $(this)

         modal.find('.modal-body #id').val(id);
         modal.find('.modal-body #nombre').val(nombre);
         modal.find('.modal-body #apellido_paterno').val(apellido_paterno);
         modal.find('.modal-body #apellido_materno').val(apellido_materno);
         modal.find('.modal-body #email').val(email);
         modal.find('.modal-body #telefono').val(telefono);
      })
    </script>
         <script type="text/javascript">
      $('#deleteModal').on('show.bs.modal',function (event) {
         var button = $(event.relatedTarget)
         var id = button.data('id')
         var modal = $(this)

         modal.find('.modal-body #id').val(id);
      })
    </script>
@endsection